# Generated by Django 5.1.2 on 2024-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0218_system_settings_enforce_verified_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='org_id',
            field=models.IntegerField(blank=True, help_text='Organization identifier for the product type', null=True),
        ),
    ]
